version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manager_php
    volumes:
      - ./manager:/var/www/html
      - postgres_data:
    environment:
      - APP_ENV=dev
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: manager_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: postgres:16
    container_name: manager_db
    environment:
      POSTGRES_USER: rajoelison
      POSTGRES_PASSWORD: IKsODOOo42K6CPSnL43aYNyBZD2A9MWI
      POSTGRES_DB: notes_etu_79yd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
